export type Job = {
  job_id: string,
  job_type_id: string,
  customer_id: string,
  job_date: Date | string | null,
  job_due_date: Date | string | null,
  job_name: string,
  job_priority: number,
  job_status: string,
  job_time_start: string,
  job_time_end: string,
  job_time_period: string,
  job_remark: string,
  cad_id: string,
  cad_date: Date | string | null,
  addby?: string,
  adddate?: Date,
  updateby?: string,
  lastupdate?: Date,
  job_parts?: JobPart[],
};

export type JobPart = {
  job_part_id: string,
  job_id: string,
  job_pre_part_ids: string[],
  job_part_name: string,
  job_part_priority: number,
  job_part_start_time: string,
  job_part_end_time: string,
  job_part_day: number,
  job_part_hour: number,
  job_part_minute: number,
  job_part_start_minute: number,
  job_part_end_minute: number,
  job_part_period: number,
  job_part_remark: string,
  job_part_status: string,
  duplicate_id: string,
  addby?: string,
  adddate?: Date,
  updateby?: string,
  lastupdate?: Date,
  job_subs?: JobSub[],
};

export type JobSub = {
  job_sub_id: string,
  job_part_id: string,
  job_id: string,
  job_pre_sub_ids: string[],
  job_sub_name: string,
  job_sub_priority: number,
  job_sub_start_time: string,
  job_sub_end_time: string,
  job_sub_day: number,
  job_sub_hour: number,
  job_sub_minute: number,
  job_sub_start_minute: number,
  job_sub_end_minute: number,
  job_sub_period: number,
  job_sub_remark: string,
  job_sub_status: string,
  duplicate_id: string,
  addby?: string,
  adddate?: Date,
  updateby?: string,
  lastupdate?: Date,
  job_processes?: JobProcess[]
};

export type JobProcess = {
  job_process_id: string,
  process_id: string,
  job_id: string,
  job_part_id: string,
  job_sub_id: string,
  job_pre_process_ids: string[],
  job_process_name: string,
  job_process_care: number,
  job_process_priority: number,
  job_process_condition_id: string,
  job_process_work_after: string,
  job_process_work_machine_id: string,
  job_process_type: string,
  job_process_start_time: string,
  job_process_end_time: string,
  job_process_start_minute: number,
  job_process_end_minute: number,
  job_process_period: number,
  job_process_setup_time: number,
  job_process_setup_finish_time: number,
  job_process_max_speed: number,
  job_process_min_speed: number,
  job_process_x: number,
  job_process_y: number,
  job_process_z: number,
  job_process_performance: number,
  job_process_day: number,
  job_process_hour: number,
  job_process_minute: number,
  job_process_status: string,
  job_process_remark: string,
  job_priority: number,
  job_part_priority: number,
  job_sub_priority: number,
  duplicate_id: string,
  addby?: string,
  adddate?: Date,
  updateby?: string,
  lastupdate?: Date,
}

export type JobPosition = {
  job_position_id: string,
  job_position_type: string,
  job_id: string,
  job_part_id: string,
  job_part_sub_id: string,
  job_part_sub_process_id: string,
  job_main: string,
  job_position: string,
}

export type JobType = {
  job_type_id: string,
  job_type_name: string,
  addby?: string,
  adddate?: Date,
  updateby?: string,
  lastupdate?: Date,
}